apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: rawhideron@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - selector:
          dnsZones:
            - duckdns.org
        dns01:
          webhook:
            groupName: acme.duckdns.org
            solverName: duckdns
            config:
              apiTokenSecretRef:
                name: duckdns-api-token
                key: token
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robot-shop-default
  namespace: robot-shop
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rawhideron.duckdns.org
      secretName: robot-shop-tls
  rules:
    - host: rawhideron.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default-404
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robot-shop-web-redirect
  namespace: robot-shop
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: /web/
spec:
  ingressClassName: nginx
  rules:
    - host: rawhideron.duckdns.org
      http:
        paths:
          - path: /web
            pathType: Exact
            backend:
              service:
                name: default-404
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: robot-shop-web
  namespace: robot-shop
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rawhideron.duckdns.org
      secretName: robot-shop-tls
  rules:
    - host: rawhideron.duckdns.org
      http:
        paths:
          - path: /web/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: web
                port:
                  number: 8080
